name: Build Docker image and push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "web/package.json"
      - "web/package-lock.json"
      - "web/app/**"
      - "web/public/**"
      - "web/next-env.d.ts"
      - "web/next.config.js"
      - "web/postcss.config.js"
      - "web/tailwind.config.ts"
      - "web/tsconfig.json"

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Check out the repo
        uses: actions/checkout@v4

      - name: DockerHub Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: DockerHub Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cis-reservation:0.0.1
